### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Aram2002** [noccu/umamusu-translate#22]
![Untitled1](https://user-images.githubusercontent.com/104795983/179762464-722f029d-0d3a-4c8c-a153-b2d13732cdc7.png)
![unknown](https://user-images.githubusercontent.com/104795983/179762677-2a6d804a-1385-4335-9619-f4d38f861b6a.png)

error  importing translation race and stuck on screen even though i already try different vpn

**Comment by noccu** [comment]
Fixed race import, thanks for bringing it to my attention.

As for stuck on loading, that's very likely not from the patch. The error simply aborts the import so nothing is changed, nor would those specific files affect game loading anyway.
Only thing I could think of is to double check you have the `config.json` for TLG (comes with the patch, in `localify/` folder) in your game folder. You can also try removing the `version.dll` to disable TLG and see if that helps. Otherwise I'm afraid you'll have to ask somewhere else regarding that.

**Comment by Aram2002** [comment]
Ok I'll try to remove version.dll and for config.json it is from localify folder

**Comment by Aram2002** [comment]
for importing race yeah its fixed but still stuck 
![Untitled](https://user-images.githubusercontent.com/104795983/179873597-48d1da79-3890-4fba-84a6-521f95b99872.png)
is it because of that? (idk tho i don't understand any of this)
cause before this it work but i forgot to batch download and then when i tried to run patch again it stuck like that

other case i want to ask. it seems my UI is too big how to fix it?
![image](https://user-images.githubusercontent.com/104795983/179873989-e841091d-2323-4ac8-93f8-4fb4fb82ffc6.png)

**Comment by noccu** [comment]
Unfortunately I have no idea about the large UI. I've only seen it once before and don't know how (or if) that person fixed it. It's not the patch itself anyway. _Maybe_ TLG, or else a game bug. 
That error looks like master.mdb didn't exist, which could explain your original error of loading the game as well if it had trouble downloading a new one or something.
Now that that is fixed, and seeing as your in-game screenshot shows translation that is part of TLG, I'll assume you enabled it again by putting version.dll back? If so, you could try playing with the resolution or UI scale settings in its `config.json`.
Other than that, I don't know.

**Comment by Aram2002** [comment]
ok the UI is fixed by changing "unlocksize" to "false" or if unlocksize is needed for patch it also can be fixed by changing "uiscale" to "0,7" for me. thanks for helping me
