### ISSUE TITLE
run.bat stuck at Found x files

### ISSUE THREAD

**Issue by Gadzzaa** [noccu/umamusu-translate#5]
![image](https://user-images.githubusercontent.com/60661008/161086419-121fa5a2-4bbd-41b0-a111-01217ba065cf.png)

**Comment by noccu** [comment]
There was one version which introduced slowdown so make sure you're on the latest one.
Otherwise, it can just take a while to finish. I've added a verbose option so if you want to check its progress or pinpoint where it fails, you can grab the latest version and run the import with the -V argument.
For the run.bat, open it in notepad and replace every `src/import.py -O` with `src/import.py -O -V`
