### ISSUE TITLE
Error while running the .BAT file.

### ISSUE THREAD

**Issue by Siiinaayu** [noccu/umamusu-translate#72]
I'm having an issue and don't really know what is the main issue behind the trouble. 

![a](https://github.com/noccu/umamusu-translate/assets/109229228/e5084f9f-4a83-4141-99b2-4f03a9ae7a9e)

**Comment by noccu** [comment]
Unsure about this one, but a bit of digging seems to indicate it is likely an issue with the connection. Perhaps your firewall/network is blocking the download, or you're using a VPN/proxy, or something to that effect?

**Comment by Siiinaayu** [comment]
I'm not quite sure too, because I've let it run bypass my windows defender (even sanctioned it off my antivirus software to avoid it getting scanned by it) and I've also tried with and without using a VPN/ proxy which still comes back to the same issue I had above.

**Comment by noccu** [comment]
I updated the [install file](../releases/tag/latest) to accommodate manual download.
Using that, you can download the [version of Mingit used by the script](https://github.com/git-for-windows/git/releases/download/v2.38.1.windows.1/MinGit-2.38.1-64-bit.zip), or if you'd like you can grab the [latest version](https://github.com/git-for-windows/git/releases) yourself, though there might be issues due to changes so that's not officially supported.
Rename the archive to `uma-temp-mingit.zip` and put it with the install script, in the same folder.  It will disappear after install or should be extracted in a folder of the same name if something else went wrong. 
Should the install fail at a network/download point again, it's very likely something in your system's configuration is causing it.
